name: SpawnPlugin
version: '${project.version}'
main: me.eranspigel.spawnplugin.SpawnPlugin
api-version: '1.20'
commands:
  setspawn:
    description: Set the spawn point
  spawn:
    description: Teleport a player at the spawn location